### ISSUE TITLE
Permit connection error in place of stream error

### ISSUE THREAD

**Issue by kazuho** [summerwind/h2spec#10]
Draft-16 5.4.1 states:
> In particular, an endpoint MAY choose to treat a stream error as a connection error.

Looking at https://github.com/summerwind/h2spec/search?utf8=✓&q=rststreamframe there seems to be three tests that expect RST_STREAM, but the two tests (6_9, 8_1) do not permit GOAWAY frames used in place.

**Comment by summerwind** [comment]
Nice catch! I had overlooked about that.
I will change codes soon.

**Comment by summerwind** [comment]
Fixed.
If you still have a problem, please reopen this issue.

**Comment by kazuho** [comment]
Thank you for the quick fix!

**Comment by kazuho** [comment]
As an afterthought, it might be worth to consider adding a _strict mode_ that permits the peer to send connection errors (or to just close the connection) in place of stream errors.

note: draft-16 6.8 states: "An endpoint might choose to close a connection without sending GOAWAY for misbehaving peers", which IMO means that it is permitted for an implementation compliant to the spec to abruptly close the connection for any of the connection errors or stream errors, taking the statement in 5.4.1 (shown above) into consideration.
