### ISSUE TITLE
test 5.1.2 expects a GOAWAY frame, should expect RST_STREAM but allow GOAWAY

### ISSUE THREAD

**Issue by shane-kearns** [summerwind/h2spec#16]
Stream errors (section 5.4.2) are raised as a RST_STREAM frame.
A stream error may be treated as a connection error (GOAWAY frame) according to section 5.4.1, so either type of error report should be accepted as a pass.

(retested with master 54dfcd3b8e0fbe17f5708e4097c81c2b4d2df190 and reviewed the code)

**Comment by summerwind** [comment]
Nice catch! I will fix it soon.

**Comment by summerwind** [comment]
Landed in 87b5f4b2e34799e09a598e9acb1bde364f2be10b.
The patch has been provided by @jthackray. thanks!
