### ISSUE TITLE
authority includes default ports

### ISSUE THREAD

**Issue by RobbySimpson** [summerwind/h2spec#29]
When using v0.0.8, the :authority pseudo-header field always appends the port, even when the default port of 443 is used for https.  While not strictly incorrect, perhaps a good new test would be to see if both (with and without port) are allowed by a server when a default port (80 or 443) is used.

i.e.:
:authority: 127.0.0.1:443
vs.
:authority: 127.0.0.1

**Comment by summerwind** [comment]
Thank you for the pointed out! 
Fixed in 659eb72693136dae0bb6e7bc986113a11ba6e1ad.
