### ISSUE TITLE
Minor wording issue with test 8.1.2.3

### ISSUE THREAD

**Issue by RobbySimpson** [summerwind/h2spec#30]
The wording for a test in section 8.1.2.3 is:
"8.1.2.3. Request Pseudo-Header Fields: Sends a HEADERS frame that is omitted mandatory pseudo-header fields"
This should be:
"8.1.2.3. Request Pseudo-Header Fields: Sends a HEADERS frame that omits mandatory pseudo-header fields"

**Comment by summerwind** [comment]
Fixed in dbe84c2b860e2497134c727f778d7fd4512103c8. Thank you!
