### ISSUE TITLE
h2spec does not send WINDOW_UPDATE frames during connection close tests

### ISSUE THREAD

**Issue by shane-kearns** [summerwind/h2spec#37]
This is a minor issue I'm opening mostly for documentation purposes.
A simple workaround is to use a smaller default document when testing.

The test cases which use TestStreamClose() will fail incorrectly if the web server's default document is larger than the flow control window (64k).
After sending 64k of data, the server is required to stop sending until it has received a WINDOW_UPDATE. As h2spec never sends this frame, the test will timeout and fail.

**Comment by summerwind** [comment]
This is a great pointed out!
I'm going to change h2spec to send WINDOW_UPDATE frame.

**Comment by summerwind** [comment]
h2spec v2.0.0 now automatically sends WINDOW_UPDATE. 
Thank you for your feedback!
