### ISSUE TITLE
Trailing header test passes when we send a RST_STREAM frame is sent

### ISSUE THREAD

**Issue by bryancall** [summerwind/h2spec#40]
Trailing header test passes when we send a RST_STREAM frame is sent before the HEADERS and DATA sent.

h2spec running:
[bcall@homer cmd]$ ./h2spec -t -k -p 4443 -h 127.0.0.1 -s 8.1
  8.1. HTTP Request/Response Exchange
    ✓ Sends a HEADERS frame as HEAD request
    ✓ Sends a HEADERS frame containing trailer part

68 tests, 2 passed, 66 skipped, 0 failed
All tests passed

Headers sent from client:
[Nov  5 22:33:00.975] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:178 (rcv_headers_frame)> (http2_cs) [2] Received HEADERS frame.
[Nov  5 22:33:00.975] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:72 (rcv_data_frame)> (http2_cs) [2] Received DATA frame.
[Nov  5 22:33:00.975] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:178 (rcv_headers_frame)> (http2_cs) [2] Received HEADERS frame.

Headers send from server:
[Nov  5 22:33:00.975] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:1012 (send_rst_stream_frame)> (http2_cs) [2] Send RST_STREAM frame.
[Nov  5 22:33:00.976] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:960 (send_headers_frame)> (http2_cs) [2] Send HEADERS frame.
[Nov  5 22:33:00.976] Server {0x7f18d532c840} DEBUG: <Http2ConnectionState.cc:895 (send_data_frame)> (http2_cs) [2] Send DATA frame

**Comment by summerwind** [comment]
Thank you for the report!
It is the bug of h2spec. I will fix it soon!

**Comment by summerwind** [comment]
Fixed in ae087617adf6580b24ac97e71746ca7bca90d11c.
This fix will be included in h2spec v1.2.0 ;)
