### ISSUE TITLE
Test 5.1: STREAM_CLOSED vs PROTOCOL_ERROR

### ISSUE THREAD

**Issue by daurnimator** [summerwind/h2spec#42]
```
× idle: Sends a DATA frame
      - The endpoint MUST treat this as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.
        Expected: GOAWAY frame (ErrorCode: PROTOCOL_ERROR)
                  Connection close
          Actual: GOAWAY frame (Length: 48, Flags: 0, ErrorCode: STREAM_CLOSED)
```
In my implementation, this check from [section 6.1](https://http2.github.io/http2-spec/#DATA) happens first:
> If a DATA frame is received whose stream is not in "open" or "half-closed (local)" state, the recipient MUST respond with a stream error (Section 5.4.2) of type STREAM_CLOSED.

Part of https://github.com/daurnimator/lua-http/milestones/h2spec%20compliance

**Comment by kazuho** [comment]
Section 6.1 says:
> DATA frames MUST be associated with a stream. If a DATA frame is received whose stream identifier field is 0x0, the recipient MUST respond with a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

Since stream_id=0 does not associate the frame with stream, you cannot decide what to do depending on the state of a stream.  Another contrary evidence to your interpretation is that sending a RST_STREAM frame with stream_id=0 is prohibited in section 6.4.

> RST_STREAM frames MUST be associated with a stream. If a RST_STREAM frame is received with a stream identifier of 0x0, the recipient MUST treat this as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

All in all, you will find many inconsistencies if you try to interpret the specification with the premise that stream_id=0 refers to a stream.  It is more natural to understand that stream_id=0 refers to the connection, not a stream.

**Comment by summerwind** [comment]
@daurnimator Thanks for the good points out. I think it’s a contradiction of the specification. I'm going to change the code to accept the both errors.

@kazuho I'm not sure about what you are saying. Are you talking about the stream_id=0??

**Comment by kazuho** [comment]
@summerwind @daurnimator Sorry my bad.  Please forgive me for the irrelevant comment.  I thought that the test was sending DATA frame with stream_id set to zero.

**Comment by kazuho** [comment]
Asked for a clarification: https://github.com/http2/http2-spec/issues/743#issuecomment-108158613

**Comment by kazuho** [comment]
It has been clarified that `GOAWAY` frame with `PROCOTOL_ERROR` must be sent in this case.
https://github.com/http2/http2-spec/issues/743#issuecomment-164794748

**Comment by summerwind** [comment]
Thank you for the follow up!
Let's close this issue.
