### ISSUE TITLE
Test 6.9.1 does not allow treating stream errors as connection errors.

### ISSUE THREAD

**Issue by Lukasa** [summerwind/h2spec#47]
Test 6.9.1 appears not to allow a connection error in place of a stream error:

```
===============================================================================
Failed tests
===============================================================================

  6.9. WINDOW_UPDATE
    6.9.1. The Flow Control Window
      × Sends multiple WINDOW_UPDATE frames on a stream increasing the flow control window to above 2^31-1
        - The endpoint MUST sends a RST_STREAM with the error code of FLOW_CONTROL_ERROR code.
          Expected: RST_STREAM frame (ErrorCode: FLOW_CONTROL_ERROR)
            Actual: GOAWAY frame (Length: 8, Flags: 0, ErrorCode: FLOW_CONTROL_ERROR)
```

This is out of line with several of the other tests which do allow this logic, as discussed in #10.

I'll see if I can provide a pull request to fix this logic.

**Comment by summerwind** [comment]
Thank you for the feedback and PR!

I agree with your opinion. But from the specs, it is not possible to determine whether these frames are allowed to treat this as a "stream error". 

> A sender MUST NOT allow a flow-control window to exceed 231-1 octets. If a sender receives a WINDOW_UPDATE that causes a flow-control window to exceed this maximum, it MUST terminate either the stream or the connection, as appropriate. For streams, the sender sends a RST_STREAM with an error code of FLOW_CONTROL_ERROR; for the connection, a GOAWAY frame with an error code of FLOW_CONTROL_ERROR is sent.

For example, in the following description of Section 6.9.2, the spec allows that the error is treated as a stream error explicitly.

> A receiver MUST treat the receipt of a WINDOW_UPDATE frame with an flow-control window increment of 0 as a stream error (Section 5.4.2) of type PROTOCOL_ERROR; errors on the connection flow-control window MUST be treated as a connection error (Section 5.4.1).

We need to ask questions about this to the editors.

**Comment by tatsuhiro-t** [comment]
The issue is, as I understand it, to allow GOAWAY as well as RST_STREAM.
I saw Martin said mentioned the possibility of treating stream error as connection error if implementation sees a value (obvious error from client like in this case) in several occasions.

**Comment by summerwind** [comment]
Okay, I decided to handle stream errors as connection errors. Let's merge #48.
Thank you guys for your feedbacks!
