### ISSUE TITLE
Show information why test failed

### ISSUE THREAD

**Issue by tatsuhiro-t** [summerwind/h2spec#5]
Currently if test fails, it just say error with read color.
It is a bit hard to debug this, since we have no way to know what was wrong.
It is extremely valuable to show some context of failure.
For example, we expected A but got B. Or we expected A but timed out.

**Comment by summerwind** [comment]
I have implemented the better output function on 3aea0c721804d6b0e68e2a549b63025a889162f1.
Thank you for your feedback and support!

![GitHub Logo](https://cloud.githubusercontent.com/assets/230145/6203647/bb15df9e-b56f-11e4-864e-fc63ac0743fb.png)

**Comment by tatsuhiro-t** [comment]
That's awesome. Thank you!
