### ISSUE TITLE
Invalid DATA frame flags for the padding test in 6.1

### ISSUE THREAD

**Issue by drhollings** [summerwind/h2spec#51]
In section 6.1, \x00\x00\x05\x00\x0b\x00\x00\x00\x01 appears as the frame header for a DATA frame in the padding test. This results in \x0b as the frame flags octet, which is invalid since a DATA frame header does not define a flag for the 0x2 bit. Perhaps it should be \x09?

From the spec:
Flags that have no defined semantics for a particular frame type MUST be ignored and MUST be left unset (0x0) when sending.

**Comment by summerwind** [comment]
You are correct. Fixed in 836fb5c8e7ec8447e7e35804ea78f60b06aafefe.
Thank you for your feedback!
