### ISSUE TITLE
Execute only selected tests

### ISSUE THREAD

**Issue by tatsuhiro-t** [summerwind/h2spec#6]
Most likely we would like to run failed test only, or just one selected test to make server log inspection easier.  curl test suite has this feature.

**Comment by summerwind** [comment]
Added `-s` option to support the partial execution of tests.
Landed in 45cb654244a411396ee56b40613322d6de553537.
If you still have a problem, please reopen this issue and tell me.

**Comment by tatsuhiro-t** [comment]
Awesome!
