### ISSUE TITLE
How to run a single spec?

### ISSUE THREAD

**Issue by georgeu2000** [summerwind/h2spec#61]
Is it possible to run a single spec?

**Comment by summerwind** [comment]
No, it isn't. But I already received some similar feedback. I'm going to support this in a future version.

**Comment by georgeu2000** [comment]
OK, thank you.

Is it possible to run a single spec file?

**Comment by summerwind** [comment]
You can use `-s` opstion to run a single section like this:

```
$ h2spec -s 3.5
```

**Comment by georgeu2000** [comment]
Oh, I see. Just like on the documentation. Thank you.

**Comment by Karm** [comment]
Hello folks, 
v2 branch seems to be missing the ```  -s: Section number on which to run the test. (Example: -s 6.1 -s 6.2)``` altogether. Is it an intentional design decision or just a missing piece open for pull requests?  @summerwind would you prefer a new approach/syntax or a simple port from the previous version is fine?

**Comment by summerwind** [comment]
@Karm Thank you for following up. Let's close.

**Comment by georgeu2000** [comment]
Thank you!!!
