### ISSUE TITLE
Send DATA frame on Idle stream

### ISSUE THREAD

**Issue by chhsiao90** [summerwind/h2spec#69]
It seems that [5_1.go](https://github.com/summerwind/h2spec/blob/master/5_1.go#L10-L22) violate [rfc7540](https://tools.ietf.org/html/rfc7540#section-6.1) and [6_1.go](https://github.com/summerwind/h2spec/blob/master/6_1.go#L25-L47)

>    DATA frames are subject to flow control and can only be sent when a
   stream is in the "open" or "half-closed (remote)" state.  The entire
   DATA frame payload is included in flow control, including the Pad
   Length and Padding fields if present.  If a DATA frame is received
   whose stream is not in "open" or "half-closed (local)" state, the
   recipient MUST respond with a stream error (Section 5.4.2) of type
   STREAM_CLOSED.

Is that the test should be removed?

**Comment by summerwind** [comment]
What do you mean by violate? 
I belive that test of 5.1 is valid according to the following spec.

[RFC 7540, 5.1](https://tools.ietf.org/html/rfc7540#section-5.1)
> Receiving any frame other than HEADERS or PRIORITY on a stream in
> this state MUST be treated as a connection error (Section 5.4.1)
> of type PROTOCOL_ERROR.

**Comment by chhsiao90** [comment]
Sorry, I miss that paragraph, my bad :(
I had just seen the description about the DATA frame, and think that ```not in "open" or "half-closed"``` including idle state.
I would read rfc more carefully, sorry for bothering you, and thanks for your reply!

**Comment by summerwind** [comment]
No problem!
Please feel free to contact us if you have any question :)
