### ISSUE TITLE
Set non-zero return code if tests fail.

### ISSUE THREAD

**Issue by Lukasa** [summerwind/h2spec#77]
I'd like to add h2spec to the hyper-h2 CI test suite, but right now the only way I can do that is by checking the output for a non-zero number of failures. It would be nicer if h2spec would return a non-zero return code when some number of tests fail so that the CI tools will automatically spot that.

**Comment by summerwind** [comment]
Thank you for reporting the issue.
This is a bug from v2.0.0. I will fix this bug in few days.

**Comment by summerwind** [comment]
Fixed in 2b4f0922ec74bec106cf36cbeda78cf6a8397f01.
Can you try with h2spec v2.1.0 please?
https://github.com/summerwind/h2spec/releases/tag/v2.1.0

**Comment by Lukasa** [comment]
A quick test suggests this works, thanks @summerwind! :sparkles:
