### ISSUE TITLE
go get .../cmd/h2spec fails with h2spec.go vs h2specd.go conflict

### ISSUE THREAD

**Issue by SpComb** [summerwind/h2spec#83]
Looks like the [`h2spec.go`](https://github.com/summerwind/h2spec/blob/master/cmd/h2spec/h2spec.go)  and [`h2specd.go`](https://github.com/summerwind/h2spec/blob/master/cmd/h2spec/h2specd.go) files are both top-level `main` files in the same package-directory. The `h2specd.go` should probably be in a separate `cmd/h2specd` package, in order to keep the package `go get`-able? 

Mind, that wouldn't respect the `glide.yaml`...

```
$ go get github.com/summerwind/h2spec/cmd/h2spec
# github.com/summerwind/h2spec/cmd/h2spec
../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2specd.go:14: VERSION redeclared in this block
	previous declaration at ../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2spec.go:14
../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2specd.go:15: COMMIT redeclared in this block
	previous declaration at ../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2spec.go:15
../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2specd.go:18: main redeclared in this block
	previous declaration at ../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2spec.go:18
../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2specd.go:55: run redeclared in this block
	previous declaration at ../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2spec.go:50
../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2specd.go:161: version redeclared in this block
	previous declaration at ../../go/src/github.com/summerwind/h2spec/cmd/h2spec/h2spec.go:143
```

**Comment by summerwind** [comment]
Currently, I don't recommend to install h2spec via `go get`. Please download release binary from Releases page.

**Comment by ioquatix** [comment]
Why doesn't it work? How do you build the releases?

**Comment by summerwind** [comment]
It is due to the directory structure. Release binary is built as follows:
https://github.com/summerwind/h2spec/blob/b3a181469923ff46ec30352eb34e89b4e55d6254/Makefile#L30-L43
