### ISSUE TITLE
Doesn't server receiving GOAWAY frame have to close the connection ?

### ISSUE THREAD

**Issue by i110** [summerwind/h2spec#92]
The following two lines expect that the server will close the connection, but in my understanding http2 specification doesn't state that, rather I think it expects the sender of GOAWAY frame will close the connection, because GOAWAY frame is used to notify the peer that the sender will initiate closing the connection. What do you think?
https://github.com/summerwind/h2spec/blob/master/generic/3_8_goaway.go#L30
https://github.com/summerwind/h2spec/blob/master/http2/7_error_codes.go#L27

**Comment by summerwind** [comment]
Correct. These test cases are invalid. However, I belive that sending a GOAWAY frame is useful for server testing. So I'd like to fix this to send PING frame after GOAWAY frame like other test case.
https://github.com/summerwind/h2spec/blob/master/client/4_1_frame_format.go#L28-L31

**Comment by summerwind** [comment]
Fixed in [v2.2.0](https://github.com/summerwind/h2spec/releases/tag/v2.2.0).
